using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace CronoSeries.ABMath.Miscellaneous
{
    /// <summary>
    ///     A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder",
        "4.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class TablesResource
    {
        private static ResourceManager resourceMan;

        [SuppressMessage("Microsoft.Performance",
            "CA1811:AvoidUncalledPrivateCode")]
        internal TablesResource()
        {
        }

        /// <summary>
        ///     Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState
            .Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp =
                        new ResourceManager("ABMath.TablesResource",
                            typeof(TablesResource).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///     Overrides the current thread's CurrentUICulture property for all
        ///     resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState
            .Advanced)]
        internal static CultureInfo Culture { get; set; }

        /// <summary>
        ///     Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///     &lt;ArrayOfDouble xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;
        ///     http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///     &lt;double&gt;1.7770360449935381&lt;/double&gt;
        ///     &lt;double&gt;2.0649378727260119&lt;/double&gt;
        ///     &lt;double&gt;2.2249514025135166&lt;/double&gt;
        ///     &lt;double&gt;2.34714305545344&lt;/double&gt;
        ///     &lt;double&gt;2.4463236337302803&lt;/double&gt;
        ///     &lt;double&gt;2.5307811910090794&lt;/double&gt;
        ///     &lt;double&gt;2.6064894814998691&lt;/double&gt;
        ///     &lt;double&gt;2.6747905707131987&lt;/double&gt;
        ///     &lt;double&gt;2.736976176724033&lt;/double&gt;
        ///     &lt;doubl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quants12 => ResourceManager.GetString("quants12", Culture);

        /// <summary>
        ///     Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///     &lt;ArrayOfDouble xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;
        ///     http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///     &lt;double&gt;2.243989168687718&lt;/double&gt;
        ///     &lt;double&gt;2.5725392624278607&lt;/double&gt;
        ///     &lt;double&gt;2.7601291286573177&lt;/double&gt;
        ///     &lt;double&gt;2.8973437146953809&lt;/double&gt;
        ///     &lt;double&gt;3.0114374331852041&lt;/double&gt;
        ///     &lt;double&gt;3.1108795781351875&lt;/double&gt;
        ///     &lt;double&gt;3.1969751720335768&lt;/double&gt;
        ///     &lt;double&gt;3.2774681560632031&lt;/double&gt;
        ///     &lt;double&gt;3.3509597643925817&lt;/double&gt;
        ///     &lt;dou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quants16 => ResourceManager.GetString("quants16", Culture);

        /// <summary>
        ///     Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///     &lt;ArrayOfDouble xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;
        ///     http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///     &lt;double&gt;2.6546340373919577&lt;/double&gt;
        ///     &lt;double&gt;3.0200378551089893&lt;/double&gt;
        ///     &lt;double&gt;3.2285146997670275&lt;/double&gt;
        ///     &lt;double&gt;3.3823886874382731&lt;/double&gt;
        ///     &lt;double&gt;3.5058967004434409&lt;/double&gt;
        ///     &lt;double&gt;3.6168662520651558&lt;/double&gt;
        ///     &lt;double&gt;3.7136387614080681&lt;/double&gt;
        ///     &lt;double&gt;3.8011956947269834&lt;/double&gt;
        ///     &lt;double&gt;3.8837465463068881&lt;/double&gt;
        ///     &lt;do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quants20 => ResourceManager.GetString("quants20", Culture);

        /// <summary>
        ///     Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///     &lt;ArrayOfDouble xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;
        ///     http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///     &lt;double&gt;3.0271422487069959&lt;/double&gt;
        ///     &lt;double&gt;3.423924675709257&lt;/double&gt;
        ///     &lt;double&gt;3.6565114726076868&lt;/double&gt;
        ///     &lt;double&gt;3.8245976728892264&lt;/double&gt;
        ///     &lt;double&gt;3.9625388537694883&lt;/double&gt;
        ///     &lt;double&gt;4.0818231572048855&lt;/double&gt;
        ///     &lt;double&gt;4.1891272871319316&lt;/double&gt;
        ///     &lt;double&gt;4.2869448755913009&lt;/double&gt;
        ///     &lt;double&gt;4.3740912660558537&lt;/double&gt;
        ///     &lt;dou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quants24 => ResourceManager.GetString("quants24", Culture);

        /// <summary>
        ///     Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///     &lt;ArrayOfDouble xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;
        ///     http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///     &lt;double&gt;3.3608453336630308&lt;/double&gt;
        ///     &lt;double&gt;3.7921548220276886&lt;/double&gt;
        ///     &lt;double&gt;4.0378032026376571&lt;/double&gt;
        ///     &lt;double&gt;4.2214492416546179&lt;/double&gt;
        ///     &lt;double&gt;4.3734724866919059&lt;/double&gt;
        ///     &lt;double&gt;4.501615270356945&lt;/double&gt;
        ///     &lt;double&gt;4.6171162221599129&lt;/double&gt;
        ///     &lt;double&gt;4.7225624242921169&lt;/double&gt;
        ///     &lt;double&gt;4.8180640453107886&lt;/double&gt;
        ///     &lt;dou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quants28 => ResourceManager.GetString("quants28", Culture);

        /// <summary>
        ///     Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///     &lt;ArrayOfDouble xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;
        ///     http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///     &lt;double&gt;0.476040643960692&lt;/double&gt;
        ///     &lt;double&gt;0.64011123704470119&lt;/double&gt;
        ///     &lt;double&gt;0.73800845762973577&lt;/double&gt;
        ///     &lt;double&gt;0.80834309682711813&lt;/double&gt;
        ///     &lt;double&gt;0.86611355209349361&lt;/double&gt;
        ///     &lt;double&gt;0.9170867323578169&lt;/double&gt;
        ///     &lt;double&gt;0.96154212403151484&lt;/double&gt;
        ///     &lt;double&gt;1.002330652525272&lt;/double&gt;
        ///     &lt;double&gt;1.0408430892014704&lt;/double&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quants4 => ResourceManager.GetString("quants4", Culture);

        /// <summary>
        ///     Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///     &lt;ArrayOfDouble xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;
        ///     http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///     &lt;double&gt;1.2045998622161065&lt;/double&gt;
        ///     &lt;double&gt;1.4455664605811802&lt;/double&gt;
        ///     &lt;double&gt;1.5798435383914469&lt;/double&gt;
        ///     &lt;double&gt;1.6804783120426885&lt;/double&gt;
        ///     &lt;double&gt;1.7651592240086913&lt;/double&gt;
        ///     &lt;double&gt;1.8350748001543868&lt;/double&gt;
        ///     &lt;double&gt;1.8971108647943549&lt;/double&gt;
        ///     &lt;double&gt;1.9533448310574579&lt;/double&gt;
        ///     &lt;double&gt;2.0053522691345553&lt;/double&gt;
        ///     &lt;do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quants8 => ResourceManager.GetString("quants8", Culture);
    }
}